name: pdf
on: [repository_dispatch, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        env: 
          PAYLOAD: ${{github.event.repository_dispatch.client_payload}}
        run: |
          echo "$PAYLOAD"
