name: pdf
on: [repository_dispatch, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "payload: ${{ github.event.client_payload.test }}\ntest: ${{ github.event.client_payload.test }}"
          echo 
