name: pdf
on: [repository_dispatch, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        env: 
          PAYLOAD: ${{github.event.client_payload}}
          PAYLOADTEST: ${{github.event.client_payload.test}}
        run: |
          echo "$PAYLOAD"
          echo "$PAYLOADTEST"
