name: pdf
on: [repository_dispatch, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: display client_payload
        run: |
          echo "payload: ${{ github.event.client_payload }}"
